# Generated by Django 5.2.16 on 2026-07-10 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalResearchRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sanitized_query', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL', 'Partial'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_requests', to='experiments.experiment')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_research_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ValidatedResearchPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated_data', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', max_length=20)),
                ('validation_errors', models.JSONField(blank=True, default=list)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('research_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='validated_package', to='ai_engine.externalresearchrequest')),
            ],
        ),
        migrations.CreateModel(
            name='InternalAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_model_name', models.CharField(blank=True, max_length=100)),
                ('twin_snapshot', models.JSONField(blank=True, default=dict)),
                ('base_calculations', models.JSONField(blank=True, default=dict)),
                ('experimental_calculations', models.JSONField(blank=True, default=dict)),
                ('provider_comparison', models.JSONField(blank=True, default=dict)),
                ('recommendation', models.TextField(blank=True)),
                ('risks', models.JSONField(blank=True, default=list)),
                ('confidence_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_internal_analyses', to=settings.AUTH_USER_MODEL)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_analyses', to='experiments.experiment')),
                ('research_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_analyses', to='ai_engine.validatedresearchpackage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProviderResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('OPENAI', 'OpenAI'), ('ANTHROPIC', 'Anthropic Claude'), ('GEMINI', 'Google Gemini'), ('GROK', 'xAI Grok')], max_length=20)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('raw_response', models.TextField(blank=True)),
                ('structured_response', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('research_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_responses', to='ai_engine.externalresearchrequest')),
            ],
            options={
                'ordering': ['provider'],
                'constraints': [models.UniqueConstraint(fields=('research_request', 'provider'), name='unique_provider_per_research_request')],
            },
        ),
    ]
