# Generated by Django 5.2.16 on 2026-07-10 18:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('density_kg_m3', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('yield_strength_mpa', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyCatalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('machine_hour_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DigitalTwin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cad_file', models.FileField(blank=True, null=True, upload_to='digital_twins/cad/')),
                ('image_file', models.FileField(blank=True, null=True, upload_to='digital_twins/images/')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=8, max_digits=14, null=True)),
                ('mass_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('production_time_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('energy_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('defect_rate_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('desired_profit_margin_percent', models.DecimalField(decimal_places=2, default=20, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_digital_twins', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_digital_twins', to=settings.AUTH_USER_MODEL)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='digital_twins', to='digital_twins.materialcatalog')),
                ('technology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='digital_twins', to='digital_twins.technologycatalog')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DigitalTwinFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.CharField(choices=[('CAD', 'CAD'), ('DRAWING', 'Drawing'), ('IMAGE', 'Image'), ('DOCUMENT', 'Document')], max_length=20)),
                ('file', models.FileField(upload_to='digital_twins/files/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('digital_twin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='digital_twins.digitaltwin')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_twin_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='digitaltwin',
            index=models.Index(fields=['part_number'], name='digital_twi_part_nu_84f865_idx'),
        ),
        migrations.AddIndex(
            model_name='digitaltwin',
            index=models.Index(fields=['created_at'], name='digital_twi_created_33f9d1_idx'),
        ),
    ]
